# Configuration constants for the addon

# audio_internal.py
PLUS_MINUS_SENSITIVITY_VOLUME = 0.02
JOG_SENSITIVITY_VOLUME = 0.05
PLUS_MINUS_SENSITIVITY_PAN = 0.05
JOG_SENSITIVITY_PAN = 0.1
PRECISION_MODE_DIVISOR = 4.0
SNAP_THRESHOLD_VOLUME = 0.05
SNAP_THRESHOLD_PAN = 0.1

# bl_cam_optics.py
JOG_SENSITIVITY_LENS = 15.0
PLUS_MINUS_SENSITIVITY_LENS = 1.0
JOG_SENSITIVITY_FOCUS = 0.5
PLUS_MINUS_SENSITIVITY_FOCUS = 0.05
JOG_SENSITIVITY_SHIFT = 0.05
PLUS_MINUS_SENSITIVITY_SHIFT = 0.01
JOG_SENSITIVITY_FSTOP = 0.5
PLUS_MINUS_SENSITIVITY_FSTOP = 0.1
JOG_SENSITIVITY_BLADES = 1.0
PLUS_MINUS_SENSITIVITY_BLADES = 1
JOG_SENSITIVITY_ROTATION = 15.0
PLUS_MINUS_SENSITIVITY_ROTATION = 2.0
JOG_SENSITIVITY_RATIO = 0.1
PLUS_MINUS_SENSITIVITY_RATIO = 0.02
PRECISION_DIVISOR = 4.0

# fades.py
MIN_FADE_DURATION = 2

# markers.py
MARKER_MOVE_SENSITIVITY_JOG = 10.0

# strips_tools.py
GRAB_BASE_SENSITIVITY = 1.0
GRAB_PROJECT_LENGTH_DIVISOR = 1000.0
OFFSET_JOG_SENSITIVITY = 10.0
OFFSET_PRECISION_DIVISOR = 4.0

# tools_extra.py
PLUS_MINUS_SENSITIVITY = 0.05
JOG_SENSITIVITY = 0.1
PLUS_MINUS_SENSITIVITY_POS = 1.0
JOG_SENSITIVITY_POS = 2.0
PLUS_MINUS_SENSITIVITY_ROT = 0.5
JOG_SENSITIVITY_ROT = 1.0
PLUS_MINUS_SENSITIVITY_ORIG = 0.01
JOG_SENSITIVITY_ORIG = 0.02
PLUS_MINUS_SENSITIVITY_ALPHA = 0.02
JOG_SENSITIVITY_ALPHA = 0.05
PLUS_MINUS_SENSITIVITY_COLOR = 0.02
JOG_SENSITIVITY_COLOR = 0.05
PLUS_MINUS_SENSITIVITY_CROP_PX = 2
JOG_SENSITIVITY_CROP_PX = 20
CROP_L_INVERT = False
CROP_R_INVERT = True
CROP_T_INVERT = True
CROP_B_INVERT = True

# tools_fx.py
SPEED_FACTOR_SENSITIVITY_JOG = 0.2
SPEED_FACTOR_SENSITIVITY_NUDGE = 0.05
SPEED_STRETCH_SENSITIVITY_JOG = 4.0
SPEED_STRETCH_SENSITIVITY_NUDGE = 1.0
SPEED_FRAME_LENGTH_SENSITIVITY_JOG = 4.0
SPEED_FRAME_LENGTH_SENSITIVITY_NUDGE = 1.0
TRANSFORM_SENSITIVITY_JOG = 0.02
TRANSFORM_SENSITIVITY_NUDGE = 0.01
TRANSFORM_ROT_SENSITIVITY_JOG = 2.0
TRANSFORM_ROT_SENSITIVITY_NUDGE = 1.0
WIPE_SENSITIVITY_JOG = 0.05
WIPE_SENSITIVITY_NUDGE = 0.02
WIPE_ANGLE_SENSITIVITY_JOG = 2.0
WIPE_ANGLE_SENSITIVITY_NUDGE = 1.0
GENERIC_FX_SENSITIVITY_JOG = 0.05
GENERIC_FX_SENSITIVITY_NUDGE = 0.02